/* USANDO CHAVE ESTRANGEIRA */

/* EM UM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA VAI PARA
A TABELA MAIS FRACA */

/* EM UM RELACIONAMENTO 1 X N A CHAVEIRA ESTRANGEIRA FICA NA TABELA N */

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE
);

CREATE TABLE TELEFONE(
	ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL'),
    NUMERO VARCHAR(12),
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
    
);

CREATE TABLE ENDERECO(
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE) 
);

SHOW TABLES;

INSERT INTO CLIENTE(NOME, CPF, SEXO, EMAIL)
VALUES
('PEDRO SILVA', '123.456.789-00', 'M', 'PEDRO_SILVA@HOTMAIL.COM'),
('PAULO SILAS', '234.567.890-12', 'M', 'PAULO.S@GMAIL.COM'),
('CELIA DOS SANTOS', '428.658.425-85', 'F', 'CELIA.STOS@HOTMAIL.COM'),
('JOAO OLIVERA', '278.356.248-75', 'M', 'J.OLIVEIRA@OUTLOOK.COM'),
('CLARA SANTANA', '158.428.365-87', 'F', 'CLARA-SANTANA@YAHOO.COM'),
('ANA HERRERA', '874.658.157-65', 'F', 'ANA_HERRERA@IG.COM.BR');

INSERT INTO CLIENTE(NOME, CPF, SEXO, EMAIL)
VALUES
('ANTONIO CAPIXABA', '587.698.412-00', 'M', NULL),
('FERNANDO HENRIQUE', '412.326.741-15','M', NULL),
('LEVI DOS ANJOS', '741.658.235-32', 'M', 'LEVI_AN@HOTMAIL.COM');

INSERT INTO ENDERECO(RUA, NUMERO, BAIRRO, CIDADE, ESTADO, ID_CLIENTE)
VALUES
('RUA A', '125', 'CENTRO', 'BELO HORIZONTE', 'MG', 2),
('RUA B', '369', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 7),
('RUA C', '698', 'JARDINS', 'SÃO PAULO', 'SP', 4),
('RUA D', '1025', 'MORUMBI', 'SÃO PAULO', 'SP', 1),
('RUA E', '9', 'ALOGOINHA', 'MACAE', 'RJ', 9);	

INSERT INTO ENDERECO(RUA, NUMERO, BAIRRO, CIDADE, ESTADO, ID_CLIENTE)
VALUES
('RUA F', '1258', 'MOEMA', 'SÃO PAULO', 'SP', 3),
('RUA G', '555', 'ESTÁCIO', 'RIO DE JANEIRO', 'RJ', 5),
('RUA H', '47', 'MARACÁS', 'BELO HORIZONTE', 'MG', 6),
('RUA I', '784', 'MORRO AZUL', 'SANTANA', 'MG', 8);

DESC TELEFONE;

INSERT INTO TELEFONE(TIPO, NUMERO, ID_CLIENTE)
VALUES
('RES', '11 37139658', 4),
('CEL', '11 912345678', 1),
('COM', '11 58946985', 3),
('RES', '32 35479875', NULL),
('CEL', '31 937138558', 2),
('COM', '32 28539658', NULL),
('RES', '21 40879875', 7),
('CEL', '21 937658558', NULL),
('COM', '21 10539658', NULL);

SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO;
SELECT * FROM TELEFONE;
