/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */

/* CONTADO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS 'QtdeRegistros' FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*) AS 'QUANTIDADE' FROM CLIENTE
GROUP BY SEXO;