/* UTILIZANDO O UPDATE E DELETE PARA ATUALIZAR/REMOVER VALORES */

SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'cibele_cristina@gmail.com'
WHERE NOME = 'Cibele';

DELETE FROM CLIENTE
WHERE NOME = 'Ana';